const BOOK="https://www.fresha.com/a/skin-sculpt-tukums-tukums-pasta-iela-11-sjn073od";
const benefits=[["Ādas tonuss","Ādas kvalitātes un tonusa uzlabošanai."],["Ķermeņa aprises","Darbam ar izvēlētām ķermeņa zonām."],["Viegluma sajūta","Procedūra labsajūtai un viegluma sajūtai."],["Labsajūta","Laiks rūpēm par savu ķermeni."]];
export default function Endosfera(){return <main className="endoPage"><header className="nav"><a className="logoSlot" href="/">S&S</a><a className="textLink backLink" href="/">← Atpakaļ</a><a className="button small" href={BOOK}>Pieteikt vizīti</a></header>
<section className="endoHero"><div><p className="eyebrow">ENDOSFĒRAS TERAPIJA</p><h1>Endosfēras<br/>terapija</h1><p className="lead">Ķermeņa procedūra ādas tonusam, ķermeņa aprisēm un labsajūtai.</p><p className="endoMeta">No 50 € · 45–75 min</p><a className="button" href={BOOK}>Pieteikt vizīti</a></div><div className="endoHeroVisual visual"/></section>
<section className="section endoBenefits"><p className="eyebrow">IEGUVUMI</p><h2>Ko tā sniedz?</h2><div className="benefitGrid">{benefits.map(([t,p])=><article key={t}><h3>{t}</h3><p>{p}</p></article>)}</div></section>
<section className="endoPricing"><div className="endoInner"><p className="eyebrow">VARIANTI</p><h2>Izvēlies procedūru</h2><div className="priceGrid"><article><h3>Problēmzonām</h3><b>45 min</b><strong>50 €</strong><p>Koncentrēta procedūra izvēlētām ķermeņa zonām.</p><a className="textLink" href={BOOK}>Pieteikt vizīti →</a></article><article><h3>Visam ķermenim</h3><b>75 min</b><strong>65 €</strong><p>Plašāka procedūra visam ķermenim.</p><a className="textLink" href={BOOK}>Pieteikt vizīti →</a></article></div></div></section>
<section className="section endoAbout"><div><p className="eyebrow">PAR PROCEDŪRU</p><h2>Par procedūru</h2><p>Detalizētu procedūras norisi un ieteikumus precizēsim kopā ar Skin & Sculpt komandu.</p></div><div className="visual"/></section>
<section className="endoProof"><div><b>5.0</b><span>Fresha vērtējums</span></div><div><b>340+</b><span>klientu vērtējumi</span></div><div><b>Tukums</b><span>Pasta iela 11</span></div></section>
<section className="endoCta"><h2>Gatava procedūrai?</h2><p>Izvēlies sev piemērotāko laiku un piesakies vizītei tiešsaistē.</p><a className="button" href={BOOK}>Pieteikt vizīti</a><small>Fresha · rezervācija tiešsaistē</small></section>
<footer className="siteFooter endoFooter"><div className="logoSlot">S&S</div><p>Pasta iela 11, Tukums<br/>© Skin & Sculpt</p></footer></main>}