"use client";
import {useEffect,useState} from "react";
const BOOK="https://www.fresha.com/a/skin-sculpt-tukums-tukums-pasta-iela-11-sjn073od";
const specialists=["Rūta","Endija","Veronika","Vanesa"];
export default function Home(){const [showBook,setShowBook]=useState(false);useEffect(()=>{const onScroll=()=>{const y=window.scrollY,h=window.innerHeight,doc=document.documentElement.scrollHeight;setShowBook(y>h*.78&&y<doc-h*1.65)};onScroll();addEventListener("scroll",onScroll,{passive:true});return()=>removeEventListener("scroll",onScroll)},[]);return <main>
<section className="heroShell">
<header className="nav"><div className="logoSlot" aria-label="Skin & Sculpt logo">S&S</div><nav><a href="#proceduras">Procedūras</a><a href="#par">Par mums</a><a href="#specialistes">Speciālistes</a></nav><a className="button small" href={BOOK}>Pieteikt vizīti</a><button className="menuButton" aria-label="Atvērt izvēlni"><span/><span/></button></header>
<div className="hero"><div className="heroContent"><p className="eyebrow">ESTĒTISKĀS KOSMETOLOĢIJAS CENTRS · TUKUMS</p><h1>Rūpes par ādu<br/>un ķermeni</h1><p className="lead">Mūsdienīgas sejas un ķermeņa procedūras ādas kvalitātei, figūrai un pašsajūtai.</p><a className="button" href={BOOK}>Pieteikt vizīti</a></div><div className="heroTrust"><span><b>5.0</b> Fresha</span><span><b>340+</b> atsauksmes</span></div></div>
</section>

<section className="section goals" id="proceduras"><div className="sectionIntro"><p className="eyebrow">PROCEDŪRAS</p><h2>Ko Tu vēlies<br/>uzlabot?</h2></div><div className="goalEditorial"><a className="goal goalLarge" href="#iecienitas"><div className="visual"/><h3>Sejas āda</h3><p>Ādas kvalitātei, mitrināšanai un atjaunošanai.</p></a><a className="goal goalTop" href="#iecienitas"><div className="visual"/><h3>Ķermeņa aprises</h3><p>Procedūras ķermeņa aprisēm un ādas kvalitātei.</p></a><a className="goal goalBottom" href="#iecienitas"><div className="visual"/><h3>Labsajūta</h3><p>Procedūras relaksācijai un pašsajūtai.</p></a></div></section>

<section className="feature" id="iecienitas"><div className="featureInner"><div className="featureCopy"><p className="eyebrow">IZCELTĀ PROCEDŪRA</p><h2>Endosfēras<br/>terapija</h2><p>Ķermeņa aprisēm, ādas kvalitātei un labsajūtai.</p><div className="featureMeta"><span>no 50 €</span><a className="textLink" href="/endosfera">Uzzināt vairāk →</a></div></div><div className="featureVisual visual"/></div></section>

<section className="section about" id="par"><div className="aboutTop"><div><p className="eyebrow">PAR SKIN & SCULPT</p><h2>Mūsdienīga pieeja<br/>rūpēm par ādu<br/>un ķermeni</h2></div><p className="aboutText">Skin & Sculpt ir estētiskās kosmetoloģijas centrs Tukumā, kas apvieno mūsdienīgas tehnoloģijas ar rūpīgu pieeju sejas un ķermeņa kopšanai.</p></div><div className="aboutVisual visual"/><div className="stats"><div><b>5.0</b><span>Fresha vērtējums</span></div><div><b>340+</b><span>klientu vērtējumi</span></div><div><b>4</b><span>speciālistes</span></div></div></section>

<section className="section team" id="specialistes"><div className="teamHead"><p className="eyebrow">KOMANDA</p><h2>Cilvēki, kuri rūpējas<br/>par Tavu pieredzi</h2></div><div className="teamEditorial">{specialists.map((name,i)=><a className={"person person"+(i+1)} href="#" key={name}><div className="portrait"/><h3>{name}</h3><p>Specializācija tiks precizēta</p></a>)}</div></section>

<section className="reviews"><div className="reviewsInner"><div className="rating"><p className="eyebrow">ATSAUKSMES</p><b>5.0</b><span>340+ klientu vērtējumi</span></div><article className="quote"><span className="quoteMark">“</span><p>Šeit būs viena izcelta reāla klienta atsauksme no Fresha.</p><footer>Klienta vārds · Fresha</footer><div className="reviewNav"><button aria-label="Iepriekšējā atsauksme">←</button><span>01 / 03</span><button aria-label="Nākamā atsauksme">→</button></div></article></div></section>

<section className="firstVisit" id="first-visit"><div><p className="eyebrow">PIRMĀ VIZĪTE</p><h2>Nezini, ar ko sākt?</h2><p>Pirmreizējā vizīte palīdzēs saprast Tavas ādas vajadzības un izvēlēties piemērotāko turpmāko kopšanu.</p><span>Konsultācija + sejas procedūra</span><strong>no 55 €</strong><a className="button" href={BOOK}>Pieteikt pirmo vizīti</a></div></section>

<section className="section contact"><div className="contactCopy"><p className="eyebrow">APMEKLĒ MŪS</p><h2>Gaidīsim Tevi<br/>Tukumā</h2><p>Pasta iela 11<br/>Tukums</p><p><a href="tel:+37120277100">20277100</a></p><p className="muted">Darba laiks tiks precizēts</p><a className="button" href={BOOK}>Pieteikt vizīti</a></div><a className="map" href="https://www.google.com/maps/search/?api=1&query=Pasta+iela+11+Tukums"><span>Pasta iela 11 · Tukums</span><small>Atvērt Google Maps →</small></a></section>

<footer className="siteFooter"><div className="logoSlot">S&S</div><div><a href="#proceduras">Procedūras</a><a href="#par">Par mums</a><a href="#specialistes">Speciālistes</a></div><div><a href="https://www.instagram.com/skinandsculpt.tukums/">Instagram</a><a href={BOOK}>Fresha</a></div><p>Pasta iela 11, Tukums<br/>© Skin & Sculpt</p></footer>
<a className={"mobileBook "+(showBook?"isVisible":"")} href={BOOK}>Pieteikt vizīti</a>
</main>}