const BOOK="https://www.fresha.com/a/skin-sculpt-tukums-tukums-pasta-iela-11-sjn073od";
const specialists=["Rūta","Endija","Veronika","Vanesa"];
const goals=[["Sejas āda","Ādas kvalitātei, mitrināšanai un atjaunošanai."],["Ķermeņa aprises","Procedūras ķermeņa aprisēm un ādas kvalitātei."],["Labsajūta","Procedūras relaksācijai un pašsajūtai."]];
export default function Home(){return <main>
<div className="heroShell">
<header className="nav"><a className="brand" href="#">Skin & Sculpt</a><nav><a href="#proceduras">Procedūras</a><a href="#par">Par mums</a><a href="#specialistes">Speciālistes</a></nav><a className="button small" href={BOOK}>Pieteikt vizīti</a><button className="menuButton" aria-label="Atvērt izvēlni"><span/><span/></button></header>
<section className="hero"><div className="heroContent"><p className="eyebrow">ESTĒTISKĀS KOSMETOLOĢIJAS CENTRS · TUKUMS</p><h1>Rūpes par ādu<br/>un ķermeni.</h1><p className="lead">Mūsdienīgas sejas un ķermeņa procedūras ādas kvalitātei, figūrai un pašsajūtai.</p><div className="actions"><a className="button" href={BOOK}>Pieteikt vizīti</a><a className="textLink" href="#proceduras">Apskatīt procedūras →</a></div><div className="trust"><b>5.0 Fresha</b><span>340+ atsauksmes</span><span>Tukums</span></div></div></section>
</div>

<section className="section goals" id="proceduras"><p className="eyebrow">PROCEDŪRAS</p><h2>Ko Tu vēlies uzlabot?</h2><p className="intro">Izvēlies savu mērķi un atrodi piemērotākās procedūras.</p><div className="goalGrid">{goals.map(([t,d])=><article className="goalCard" key={t}><div className="imageFrame"/><h3>{t}</h3><p>{d}</p><a className="textLink" href="#iecienitas">Apskatīt procedūras →</a></article>)}</div></section>

<section className="section popular" id="iecienitas"><div className="sectionHead"><p className="eyebrow">IECIENĪTĀKĀS</p><h2>Iecienītākās procedūras</h2></div><div className="popularGrid"><article className="featuredProcedure"><div className="imageFrame"/><div className="procedureCopy"><p className="eyebrow">ĶERMENIM</p><h3>Endosfēras terapija</h3><p>Ķermeņa aprisēm, ādas kvalitātei un labsajūtai.</p><div><span>no 50 €</span><a className="textLink" href="/endosfera">Uzzināt vairāk →</a></div></div></article><div className="secondaryProcedures"><article><p className="eyebrow">SEJAI</p><h3>Sejas procedūras</h3><p>Ādas kvalitātei un kopšanai.</p><a className="textLink" href={BOOK}>Pieteikt vizīti →</a></article><article><p className="eyebrow">PIRMĀ VIZĪTE</p><h3>Konsultācija + procedūra</h3><p>no 55 €</p><a className="textLink" href={BOOK}>Pieteikt vizīti →</a></article></div></div></section>

<section className="section about" id="par"><div className="aboutImage imageFrame"/><div className="aboutCopy"><p className="eyebrow">PAR CENTRU</p><h2>Par Skin & Sculpt</h2><p className="intro">Skin & Sculpt ir estētiskās kosmetoloģijas centrs Tukumā, kas apvieno mūsdienīgas tehnoloģijas ar rūpīgu pieeju sejas un ķermeņa kopšanai.</p><div className="stats"><div><b>5.0</b><span>Fresha vērtējums</span></div><div><b>340+</b><span>klientu vērtējumi</span></div><div><b>4</b><span>speciālistes</span></div></div></div></section>

<section className="section team" id="specialistes"><p className="eyebrow">KOMANDA</p><h2>Iepazīsti speciālistes</h2><div className="teamGrid">{specialists.map(n=><a className="person" href="#" key={n}><div className="portrait"/><h3>{n}</h3><p>Specializācija tiks precizēta</p><span className="textLink">Iepazīt speciālisti →</span></a>)}</div></section>

<section className="section testimonials"><div className="reviewIntro"><p className="eyebrow">ATSAUKSMES</p><h2>5.0 / 5</h2><p>340+ klientu vērtējumi Fresha</p><a className="textLink" href={BOOK}>Lasīt atsauksmes →</a></div><div className="reviewLayout"><article className="reviewMain"><div className="stars">★★★★★</div><p>Šeit būs viena izcelta reāla klienta atsauksme no Fresha.</p><span>Fresha atsauksme</span></article><div className="reviewSmall"><article><div className="stars">★★★★★</div><p>Reāla klienta atsauksme.</p><span>Fresha</span></article><article><div className="stars">★★★★★</div><p>Reāla klienta atsauksme.</p><span>Fresha</span></article></div></div></section>

<section className="firstVisit"><div className="firstVisitInner"><div className="firstVisitCopy"><p className="eyebrow">PIRMĀ VIZĪTE</p><h2>Nezini, ar ko sākt?</h2><p>Pirmreizējā vizīte palīdzēs saprast Tavas ādas vajadzības un izvēlēties piemērotāko turpmāko kopšanu.</p><span>Konsultācija + sejas procedūra</span><strong>no 55 €</strong><a className="button" href={BOOK}>Pieteikt pirmo vizīti</a></div><div className="firstVisitImage imageFrame"/></div></section>

<section className="section contact"><div className="contactCopy"><p className="eyebrow">TUKUMS</p><h2>Gaidīsim Tevi Tukumā.</h2><div className="contactDetails"><p>Pasta iela 11, Tukums</p><p><a href="tel:+37120277100">20277100</a></p><p>Darba laiks tiks precizēts</p></div><a className="button" href={BOOK}>Pieteikt vizīti</a></div><a className="map" href="https://www.google.com/maps/search/?api=1&query=Pasta+iela+11+Tukums" aria-label="Atvērt adresi Google Maps"><span>Pasta iela 11 · Tukums</span><small>Atvērt Google Maps →</small></a></section>

<footer><a className="footerBrand" href="#">Skin & Sculpt</a><div className="footerLinks"><a href="#proceduras">Procedūras</a><a href="#par">Par mums</a><a href="#specialistes">Speciālistes</a></div><div className="footerLinks"><a href="https://www.instagram.com/skinandsculpt.tukums/">Instagram</a><a href={BOOK}>Fresha</a></div><div className="footerAddress">Pasta iela 11, Tukums<br/>© Skin & Sculpt</div></footer>
<a className="mobileBook" href={BOOK}>Pieteikt vizīti</a>
</main>}