const BOOK="https://www.fresha.com/a/skin-sculpt-tukums-tukums-pasta-iela-11-sjn073od";
const specialists=["Rūta","Endija","Veronika","Vanesa"];
export default function Home(){return <main>
<div className="heroShell">
<header className="nav"><a className="brand" href="#">Skin & Sculpt</a><nav><a href="#proceduras">Procedūras</a><a href="#par">Par mums</a><a href="#specialistes">Speciālistes</a></nav><a className="button small" href={BOOK}>Pieteikt vizīti</a><button className="menuButton" aria-label="Atvērt izvēlni"><span/><span/></button></header>
<section className="hero"><div className="heroContent"><p className="eyebrow">ESTĒTISKĀS KOSMETOLOĢIJAS CENTRS · TUKUMS</p><h1>Rūpes par ādu<br/>un ķermeni.</h1><p className="lead">Mūsdienīgas sejas un ķermeņa procedūras ādas kvalitātei, figūrai un pašsajūtai.</p><div className="actions"><a className="button" href={BOOK}>Pieteikt vizīti</a><a className="textLink" href="#proceduras">Apskatīt procedūras →</a></div><div className="trust"><b>5.0 Fresha</b><span>340+ atsauksmes</span><span>Tukums</span></div></div></section>
</div>
<section className="section" id="proceduras"><p className="eyebrow">PROCEDŪRAS</p><h2>Ko Tu vēlies uzlabot?</h2><p className="intro">Izvēlies savu mērķi un atrodi piemērotākās procedūras.</p><div className="grid three">{[["Sejas āda","Ādas kvalitātei, mitrināšanai un atjaunošanai."],["Ķermeņa aprises","Procedūras ķermeņa aprisēm un ādas kvalitātei."],["Labsajūta","Procedūras relaksācijai un pašsajūtai."]].map(([t,d])=><article className="card" key={t}><div className="imageSlot"/><h3>{t}</h3><p>{d}</p><a className="textLink" href="#iecienitas">Apskatīt procedūras →</a></article>)}</div></section>
<section className="section alt" id="iecienitas"><p className="eyebrow">IECIENĪTĀKĀS</p><h2>Iecienītākās procedūras</h2><div className="grid three"><article className="procedure"><p>ĶERMENIM</p><h3>Endosfēras terapija</h3><span>no 50 €</span><a className="textLink" href="/endosfera">Uzzināt vairāk →</a></article><article className="procedure"><p>SEJAI</p><h3>Sejas procedūras</h3><span>Individuāli izvēlēta kopšana</span><a className="textLink" href={BOOK}>Pieteikt vizīti →</a></article><article className="procedure"><p>PIRMĀ VIZĪTE</p><h3>Konsultācija + procedūra</h3><span>no 55 €</span><a className="textLink" href={BOOK}>Pieteikt vizīti →</a></article></div></section>
<section className="split section" id="par"><div className="placeholder">Jūsu izvēlētais attēls</div><div><p className="eyebrow">PAR CENTRU</p><h2>Par Skin & Sculpt</h2><p className="intro">Skin & Sculpt ir estētiskās kosmetoloģijas centrs Tukumā, kas apvieno mūsdienīgas tehnoloģijas ar rūpīgu pieeju sejas un ķermeņa kopšanai.</p><div className="stats"><div><b>5.0</b><span>Fresha vērtējums</span></div><div><b>340+</b><span>klientu vērtējumi</span></div><div><b>4</b><span>speciālistes</span></div></div></div></section>
<section className="section" id="specialistes"><p className="eyebrow">KOMANDA</p><h2>Iepazīsti speciālistes</h2><div className="grid four">{specialists.map(n=><article className="person" key={n}><div className="portrait">Foto</div><h3>{n}</h3></article>)}</div></section>
<section className="reviews section"><div><p className="eyebrow">ATSAUKSMES</p><h2>5.0 / 5</h2><p>340+ klientu vērtējumi Fresha</p></div><a className="textLink" href={BOOK}>Lasīt atsauksmes →</a></section>
<section className="cta section"><p className="eyebrow">PIRMĀ VIZĪTE</p><h2>Nezini, ar ko sākt?</h2><p>Pirmreizējā vizīte palīdzēs saprast Tavas ādas vajadzības un izvēlēties piemērotāko turpmāko kopšanu.</p><strong>no 55 €</strong><a className="button" href={BOOK}>Pieteikt pirmo vizīti</a></section>
<section className="section contact"><div><p className="eyebrow">TUKUMS</p><h2>Gaidīsim Tevi Tukumā.</h2><p>Pasta iela 11, Tukums<br/>20277100</p><a className="button" href={BOOK}>Pieteikt vizīti</a></div><div className="map">Kartes vieta</div></section>
<footer><span>Skin & Sculpt</span><span>Estētiskās kosmetoloģijas centrs Tukumā</span></footer><a className="mobileBook" href={BOOK}>Pieteikt vizīti</a>
</main>}